development: 
  cloud_name: "dc95ulkel"
  api_key: "895931444218721"
  api_secret: "a9wa-W-qz5nrqzm6_qs4HCR3KUo"
  secure: true

production:
  cloud_name: "dc95ulkel"
  api_key: "895931444218721"
  api_secret: "a9wa-W-qz5nrqzm6_qs4HCR3KUo"
  secure:true